export const heroContainer = {
  bgColor: "#38aaa3",
  backgroundSize: "cover",
  backgroundPosition: "50%",
  backgroundBlendMode: "multiply",
  color: "white",
  textAlign: "center",
  px: "5rem",
  mb: "1rem",
  overflow: "hidden",
  maxH: "50vh",
  minH: "50vh",
  pt: 12,
  _before: {
    content: '""',
    position: "fixed",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
};
